### ISSUE TITLE
Curly braces vanish

### ISSUE THREAD

**Issue by strakaps** [saeidamiri1/rbox#10]
When I enable rbox, curly braces vanish in .R files and functions become unreadable. Any hints?

**Comment by saeidamiri1** [comment]
Paste the codes\scripts that you used, because I have not seen such problems?

**Comment by strakaps** [comment]
Here's a screenshot, because if I paste the curly braces appear again...

![no-braces](https://user-images.githubusercontent.com/10371957/38447642-2b453136-3a31-11e8-89c8-38dd547eaf59.png)

**Comment by saeidamiri1** [comment]
I think the problem is the color of the curly braces, we use Atom with the black color, but you are using Atom with the white color. 
You can easily change the color of the curly braces; go to 
.atom>packages>rbox>styles>rbox.less
The color of the curly braces is defined under 
  .syntax--curlybraces{
    color: #f4f4f4;
  }
Change it to another color, for instance changes it to light green 
  .syntax--curlybraces{
    color: #699;
  }

I attach two files, first one shows the curly braces work well, the second one show how to change
the color. 
I will change the color of the curly braces in the next version of Rbox.

![untitled](https://user-images.githubusercontent.com/19543946/38448898-63e5f896-39d6-11e8-8f87-0eacbc139293.gif)

![untitled2](https://user-images.githubusercontent.com/19543946/38448900-68d4b3d8-39d6-11e8-8335-da20699863d9.gif)

**Comment by strakaps** [comment]
Yep that worked, thanks!
